name: SequenceTagging
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.4
  - anaconda
  - tensorflow-gpu
  - pip:
    #- tf-metrics==0.0.1
    - git+https://github.com/guillaumegenthial/tf_metrics.git
    
# Notes:
# tf-metrics come from a public git repo, installed using the following command
# pip install git+https://github.com/guillaumegenthial/tf_metrics.git
